### ISSUE TITLE
Doesn't take in to account having a newsletter signup card

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/canonicalwebteam.blog#115]
The third item on https://snapcraft.io/blog is replaced by the newsletter sign up form. The blog module should be able to adjust it's offsets to accomodate an extra item as having a newsletter signup is a common pattern (https://ubuntu.com/blog), currently it simply replaces a blog post!?

See for the messy way I implemented it in snapcraft: https://github.com/canonical-web-and-design/snapcraft.io/pull/2119/files#diff-4e6fc427b5a0fb3861c0230dcb245caeL46

**Comment by Lukewh** [comment]
This is also now affecting jaas.ai

**Comment by jpmartinspt** [comment]
You can now configure the number of articles you want to pull per page. That should solve this issue, unless we only want tho show the signup card in the first page.

**Comment by tbille** [comment]
This seems to be fixed.

**Comment by Lukewh** [comment]
If the solution is "Have a newsletter signup form on every page" this isn't fixed.

**Comment by solazio** [comment]
@tbille @jpmartinspt this is still an issue on snapcraft.io and ubuntu.com (maybe on others as well). The last post on the first page is showed as the first post on the second page.

**Comment by carkod** [comment]
it's been almost 2 years. @Lukewh @jkfran , do guys still see this issue?

**Comment by Lukewh** [comment]
@carkod, yeath this is still an issue. snapcraft is missing "KDE snaps performance revving up":

Snapcraft.io with newsletter sign up:
![image](https://user-images.githubusercontent.com/479384/167672006-b0e7efa6-6f25-498d-868f-618a9c60a047.png)

Ubuntu.com without:
![image](https://user-images.githubusercontent.com/479384/167672220-e1b302b8-2fdb-4a1b-9f04-ffa84af70b65.png)
